name: Install Terraform with tfenv

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl

    - name: Install tfenv
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo "$HOME/.tfenv/bin" >> $GITHUB_PATH

    - name: Install Terraform with tfenv
      run: |
        tfenv install latest
        tfenv use latest
        terraform --version

    - name: Verify Terraform installation
      run: terraform --version

    - name: Check the current path and sub dirs
      run: |
        pwd
        ls -l

